version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - webappnetwork
  api:
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge